DECLARE
  e EXCEPTION;
  PRAGMA EXCEPTION_INIT(e, -942);
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EMP_TEST PURGE';
EXCEPTION WHEN e THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PRODUCT PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STUDENTS PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
CREATE TABLE EMP_TEST ( NAME VARCHAR2(100) );
INSERT INTO EMP_TEST (NAME) VALUES ('   Alice   ');
INSERT INTO EMP_TEST (NAME) VALUES ('  Bob');
INSERT INTO EMP_TEST (NAME) VALUES ('Charlie   ');
INSERT INTO EMP_TEST (NAME) VALUES ('   *Diana*   ');
COMMIT;
SELECT NAME, TRIM(NAME) FROM EMP_TEST;
SELECT NAME, LTRIM(NAME) FROM EMP_TEST;
SELECT NAME, RTRIM(NAME) FROM EMP_TEST;
SELECT NAME, TRIM('*' FROM TRIM(NAME)) FROM EMP_TEST;
SELECT REPLACE('database','a','@') FROM dual;
SELECT REPLACE('This is the old version','old','new') FROM dual;
CREATE TABLE PRODUCT ( PRODUCT_NAME VARCHAR2(100) NOT NULL );
INSERT INTO PRODUCT (PRODUCT_NAME) VALUES ('Laptop');
INSERT INTO PRODUCT (PRODUCT_NAME) VALUES ('Phone');
INSERT INTO PRODUCT (PRODUCT_NAME) VALUES ('Headphones');
COMMIT;
SELECT PRODUCT_NAME, LPAD(PRODUCT_NAME,15,'*') FROM PRODUCT;
SELECT PRODUCT_NAME, RPAD(PRODUCT_NAME,15,'#') FROM PRODUCT;
SELECT TO_CHAR(SYSDATE,'DD-MON-YYYY') FROM dual;
SELECT TO_CHAR(SYSDATE,'Month YYYY') FROM dual;
SELECT TO_CHAR(12345.67,'FM9,999,999,990.00') FROM dual;
SELECT TO_CHAR(3500,'L9,999.00') FROM dual;
CREATE TABLE STUDENTS ( NAME VARCHAR2(100) NOT NULL, MARKS NUMBER(5,2) NOT NULL );
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Ahmed',95);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Mona',82);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Khaled',76);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Sara',68);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Laila',89);
COMMIT;
SELECT NAME, MARKS,
       CASE
         WHEN MARKS >= 90 THEN 'A'
         WHEN MARKS BETWEEN 80 AND 89.9999 THEN 'B'
         WHEN MARKS BETWEEN 70 AND 79.9999 THEN 'C'
         ELSE 'F'
       END
FROM STUDENTS
ORDER BY MARKS DESC;
